"""add github oauth tokens to users

Revision ID: 039291ec5284
Revises: 0539ded54b62
Create Date: 2026-08-11 00:10:39.118604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '039291ec5284'
down_revision: Union[str, Sequence[str], None] = '0539ded54b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_access_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('github_refresh_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('github_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_token_expires_at')
    op.drop_column('users', 'github_refresh_token')
    op.drop_column('users', 'github_access_token')
    # ### end Alembic commands ###
