"""Update code chunk schema

Revision ID: 0539ded54b62
Revises: 295559bea4ef
Create Date: 2026-08-08 07:37:36.345085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0539ded54b62'
down_revision: Union[str, Sequence[str], None] = '295559bea4ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_chunks_repository_id'), table_name='code_chunks')
    op.drop_column('code_chunks', 'start_line')
    op.drop_column('code_chunks', 'end_line')
    op.drop_column('embeddings', 'model')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('model', postgresql.ENUM('GPT_OSS', 'GEMINI_EMBEDDING', name='aimodel'), autoincrement=False, nullable=False))
    op.add_column('code_chunks', sa.Column('end_line', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('code_chunks', sa.Column('start_line', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_code_chunks_repository_id'), 'code_chunks', ['repository_id'], unique=False)
    # ### end Alembic commands ###
