"""Add repository ingestion statuses

Revision ID: 195876817eb2
Revises: 39994d9decca
Create Date: 2026-08-22 05:04:45.517825

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "195876817eb2"
down_revision: Union[str, Sequence[str], None] = "39994d9decca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE repositorystatus ADD VALUE IF NOT EXISTS 'CLONING'")
    op.execute("ALTER TYPE repositorystatus ADD VALUE IF NOT EXISTS 'CHUNKING'")
    op.execute("ALTER TYPE repositorystatus ADD VALUE IF NOT EXISTS 'EMBEDDING'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
