"""add github installation states

Revision ID: 3507b8940b0a
Revises: 52ec83c32378
Create Date: 2026-08-11 00:32:33.429562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3507b8940b0a'
down_revision: Union[str, Sequence[str], None] = '52ec83c32378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_installation_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_installation_states_state'), 'github_installation_states', ['state'], unique=True)
    op.create_index(op.f('ix_github_installation_states_user_id'), 'github_installation_states', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_installation_states_user_id'), table_name='github_installation_states')
    op.drop_index(op.f('ix_github_installation_states_state'), table_name='github_installation_states')
    op.drop_table('github_installation_states')
    # ### end Alembic commands ###
